### ISSUE TITLE
@okta/openapi not visible on GitHub

### ISSUE THREAD

**Issue by mcandre** [okta/okta-sdk-nodejs#106]
A critical dependency of @okta/okta-sdk-nodejs, @okta/openapi, is not visible on GitHub. Even though documentation on NPM instructs users to clone that repository.

**Comment by swiftone** [comment]
@mcandre - thanks for the comment.  You are correct, the @okta/openapi repo is currently private.  Can you elaborate on the confusing documentation?  Does it mention cloning @okta/openapi somewhere, or is the confusion just that it is a devDependency of this repo?

**Comment by swiftone** [comment]
@mcandre - through the valiant efforts of Okta devs that are not me, the code behind @okta/openapi is now publicly visible here: https://github.com/okta/okta-management-openapi-spec
