### ISSUE TITLE
Change log for the version 3

### ISSUE THREAD

**Issue by rafakwolf** [okta/okta-sdk-nodejs#121]
I'm seeking the version 3 changelogs, there are any documentations?
Thanks

**Comment by swiftone** [comment]
You can see the details here: https://github.com/okta/okta-sdk-nodejs/blob/master/CHANGELOG.md

We missed pushing out a set of release notes on github for 3.0 (we did for 3.1), but as we haven't figured out how to avoid confusion when backfilling releases on github (see how 2.1 is posted as more recent than 3.1) we're avoiding releasing a set of release notes for 3.0.

Sorry for the confusion, hopefully we've figured out how to avoid this confusion in the future.
