### ISSUE TITLE
Reactivate user endpoint implementation missing

### ISSUE THREAD

**Issue by mcarriere** [okta/okta-sdk-nodejs#125]
It seems the https://developer.okta.com/docs/reference/api/users/#reactivate-user endpoint hasn't been implemented in the nodejs SDK.

Would it be possible to add it?

I'd give it a try myself but it seems that the repo for https://www.npmjs.com/package/@okta/openapi isn't public.

Thanks

**Comment by swiftone** [comment]
@mcarriere - Thanks for the report!

Expanding the SDK to cover additional endpoints is something that we are currently working on.  I can't promise any timeline, but I can assure you it is not being ignored.

**Comment by oleksandrpravosudko-okta** [comment]
@mcarriere `reactivateUser` method was added in v4.0.0 - please let us know if you have any issues using it.
