### ISSUE TITLE
getLogs prints out the nodejs client used to fetch the log, not the client field of the EventLog

### ISSUE THREAD

**Issue by odedpeer** [okta/okta-sdk-nodejs#129]
I am using `getLogs` to get SystemLog records.
I noticed that the `client` field in the resulting collection is the HTTP client used to fetch the SystemLog records, not the value of the `client` field of the record itself.

I see you re-assign the client field of the json, so that the client field stores an HTTP client and It is used to allow resource models to execute http calls, like `user.listUsers`.
This overwrites the `client` field of `LogEvent`.
https://github.com/okta/okta-sdk-nodejs/blob/83160260e40e65b2ebb1f5dfd7cfdc81c056b8c9/src/resource.js#L19
https://github.com/okta/okta-sdk-nodejs/blob/83160260e40e65b2ebb1f5dfd7cfdc81c056b8c9/src/models/LogEvent.js#L56

Besides not getting the actual data I need to use this actually opens up a major security issue since the HTTP `client` field includes the API token information, which is a private secret and shouldn't be printed when I print a SystemLog record.

**Comment by swiftone** [comment]
@odedpeer - Thanks for the report and detailed breakdown.  

Internal-ref: OKTA-279654

**Comment by oleksandrpravosudko-okta** [comment]
This issue is fixed in SDK versions >=4.0.0
