### ISSUE TITLE
OpenAPI spec has incorrect type for log events

### ISSUE THREAD

**Issue by johanbrandhorst** [okta/okta-sdk-nodejs#134]
Wanted to raise this against github.com/okta/openapi, but seeing as that's private, I figured this was the next best place.

The `LogAuthenticationContext.credentialProvider` and `LogAuthenticationContext.credentialType` are both specified as arrays in the OpenAPI spec, however the API docs (https://developer.okta.com/docs/reference/api/system-log/#logevent-object) and the API response itself returns one of an enumeration of strings or JSON `null`.

This is affecting all the Okta SDK's I've looked at, so I expect no one is currently able to use the LogEvent API call successfully.

Java SDK: https://github.com/okta/okta-sdk-java/issues/358
Go SDK: https://github.com/okta/okta-sdk-golang/issues/65.

I'd be happy to make the openapi spec changes myself but since the repo is private there's not much I can do.

**Comment by swiftone** [comment]
@johanbrandhorst - Thanks for the very detailed report!  I'll note this for the upstream repo and poke the other language SDK maintainer teams.

**Comment by johanbrandhorst** [comment]
> @johanbrandhorst - Thanks for the very detailed report! I'll note this for the upstream repo and poke the other language SDK maintainer teams.

Awesome, thanks for the quick response!

**Comment by bretterer** [comment]
@johanbrandhorst Thank you for the report here. This has been updated in our latest spec work and will be updated in our SDK's in the next major release.  This release will also include all documented endpoints that are on developer.okta.com/docs

**Comment by swiftone** [comment]
Just to update: This will be addressed in our next _major_ release (as mentioned above) - we just released a minor update that did not yet address this.  The major release is currently being worked on.
