### ISSUE TITLE
Support Parallel build in travis

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/okta-sdk-nodejs#179]
Is that possible to run script in parallel for multiple node platform? looks like it's running in sequence now

```
node_js:
- '10'
- '12'
```

**Comment by swiftone** [comment]
Internal ref: OKTA-319583

**Comment by shuowu** [comment]
@haishengwu-okta The CI for okta-sdk-nodejs has been moved to bacon. It probably still run in sequence to fight against some test flakiness (shared resources).
