### ISSUE TITLE
flat 2.0.1 is deprecated

### ISSUE THREAD

**Issue by eberttc** [okta/okta-sdk-nodejs#195]
Hi,

flat 2.0.1 is used as a dependency  in package.json.

Currently our scan in fortify show us flat as a dependency with vulnerability https://www.npmjs.com/package/flat/v/2.0.1

is there any plan to upgrade version of that dependency.?

**Comment by aarongranick-okta** [comment]
@eberttc Thanks for reporting this issue. We will update this dependency. Internal ref: OKTA-323250

**Comment by eberttc** [comment]
thanks @aarongranick-okta for quick response. Do you know when will be next release approx?

**Comment by rdegges** [comment]
Hey @aarongranick-okta, is this issue safe to close since your update was merged?

**Comment by aarongranick-okta** [comment]
@rdegges @eberttc Update has been pushed, closing this issue.

**Comment by eberttc** [comment]
Hi @aarongranick-okta , I don't find a 3.3.x with this fix. and the last release 4.1.1  don't have this fix as well . When do you plan to release this changes?

**Comment by aarongranick-okta** [comment]
@eberttc Looks like an oversight. We will release a new version 4.2 with this update

**Comment by eberttc** [comment]
is possible to have this fix in release 3.3.1 ?

**Comment by aarongranick-okta** [comment]
@eberttc Fix was released in version 3.3.2

**Comment by eberttc** [comment]
Great @aarongranick-okta
