### ISSUE TITLE
getUser hangs if id is an empty string

### ISSUE THREAD

**Issue by dncrews** [okta/okta-sdk-nodejs#200]
We realized we needed to add some defensive programming on our end to make sure this doesn't happen, but it's likely something you could hopefully prevent for everyone else.

## What did you do?

```js
const Client = require('@okta/okta-sdk-nodejs');

const client = new Client.Client({ orgUrl: '//', token: '//' });

client.getUser('')
  .then((response) => {
    console.info({ response });
  })
  .catch((error) => {
    console.error({ error });
  });
```

## Expected results

Since this is a promise, I would expect this to reject with some error. Since it is a promise, it should resolve or reject or something.

## Actual results

The request happens in the background, but the promise never resolves or rejects. The script just runs and exits without ever logging anything.

**Comment by shuowu** [comment]
@dncrews Thanks for reporting the issue!

Internal Ref: OKTA-332240

**Comment by GirkovArpa** [comment]
Why is there a $50 bounty for this issue at [bountysource](https://www.bountysource.com/issues/93226249-getuser-hangs-if-id-is-an-empty-string?show_profile_modal=1), given that it's marked as closed here?

**Comment by swiftone** [comment]
That's a question for @dncrews, I suppose

**Comment by dncrews** [comment]
@swiftone why is that a question for me? I don't manage Okta bountysource.
