### ISSUE TITLE
No support for authentication

### ISSUE THREAD

**Issue by SwastikGupta** [okta/okta-sdk-nodejs#22]
no support to integrate authentication with node app using express

**Comment by jongear** [comment]
Bump, is there a timeline for authentication support?

**Comment by kybarg** [comment]
I think now auth handled via separate package https://github.com/okta/okta-auth-js

**Comment by jongear** [comment]
That's a front-end package. If you attempt to authenticate in node you will get window exceptions because it's trying to open browser windows

**Comment by kybarg** [comment]
@jongear haven't tested but that should work for node.js
```javascript
var okta = require('@okta/okta-sdk-nodejs');
var express = require('express')

var app = express()

app.post('/login', (req, res) => {
  client.http.postJson(`${apiUrl}/authn`, {
    body: {
      username: req.body.email,
      password: req.body.password,
    }
  })
    .then((session) => {
      console.log(session)
    })
    .catch((err) => {
      console.log(err)
    });
})
```

**Comment by omgitstom** [comment]
@jongear: What is your use case? What is the reason why you can't use Auth JS SDK in the pages returned by express?

I haven't made a final decision if we are going to support the [Authentication API](https://developer.okta.com/docs/api/resources/authn.html) in this SDK.  The way that I am thinking about it is keeping the AuthN API/SDK concerns as a client concern, and keep this SDK primarily CRUD operations for Okta objects.

We may in the future we may build an AuthN SDK for NodeJS,  I would love to get your feedback on needing the [Authentication API](https://developer.okta.com/docs/api/resources/authn.html) in Express or NodeJS.

**Comment by jongear** [comment]
@omgitstom thanks for responding. 

Our UI layer is detached from the API layer of our application, so simply authenticating on the client will not work for us.  We are looking to back our UI as well as our API with Okta. The reason we would like authentication support at the Node sdk level is that we would like to use the same security store to secure our API so that our endpoints are not available to the public.  We realize that we could create a separate authentication mechanism for this purpose but that seems to defeat the general purpose of investing in Okta.  For now, we have gone down the road of creating a slim middleware to authenticate request tokens on the API against Okta.

**Comment by babadofar** [comment]
@jongear  Any chance you would share the code for that middleware? I would not be surprised if there are others  who want to authenticate at the API level. In a sort of micro-services manner, if you know what I mean.

**Comment by robertjd** [comment]
I'm not sure if @jongear is referring to access tokens that are minted by Okta or something custom to his application, but if the former we now have a token validation library that can be used for this:

https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier

If you scroll down to the server section of this Express quickstart example you can see some example middleware that uses it:

https://developer.okta.com/quickstart/#/widget/nodejs/express

Let me know if this helps?

**Comment by alansikora** [comment]
I think that assuming frontends are always going to be responsible for the authentication is not correct @omgitstom.

I currently have a system that does not have frontend at all, but we have an app that uses OKTA. I'm using @kybarg's solution (thanks for that) for now, but it is not ideal.

**Comment by jongear** [comment]
@babadofar our workaround was to manually call `POST Introspect` on the okta auth server from our Node API server.  Last time I ventured into Okta's tooling it looked like they were purely concerned with Node tooling from a frontend facing perspective.  Which neglects users in my situation where we run a NodeJs powered API that is completely disjoint from any frontend verification.  Where we would like to take in an okta token, introspect it and perform actionable events upon it

NodeJS serverside Okta token introspect api call:
```javascript
  async introspect (token) {
    const introspectOptions = {
      uri: `${config.oktaSettings.orgUrl}/oauth2/${config.oktaSettings.authServerId}/v1/introspect`,
      method: 'POST',
      headers: {
        accept: 'application/json',
        'content-type': 'application/x-www-form-urlencoded',
        authorization: 'Basic ' + btoa(config.oktaSettings.clientId + ':' + config.oktaSettings.clientSecret)
      },
      form: { token: token, token_type_hint: 'access_token' }
    }

    const introspectBody = await rp(introspectOptions)
    const introspectObj = JSON.parse(introspectBody)

    return introspectObj
  }
```

Thanks @robertjd we will look into the `jwt-verifier` library to see if it meets our needs.  Much appreciated!

**Comment by babadofar** [comment]
Our solution was born out of old stormpath nodejs sdks, which used to work well for us. We got rid of  stormpath dependencies by using a combo of the jwt-verifier library, and one Call to the Authn API to log the user in at our server side.

**Comment by nbarbettini** [comment]
Thanks for the feedback everybody! We've started work on making backend Authentication API calls easier in Java, and I expect to follow that with better Node support. I'll keep everyone posted here.

**Comment by manueltanzi-okta** [comment]
@SwastikGupta @jongear @kybarg @babadofar @alansikora 

Good News! 

We released the Okta AuthN SDK as a part of the okta-auth-js library, check it out!

https://github.com/okta/okta-auth-js#node-js-usage
