### ISSUE TITLE
Add method for updating profile mapping

### ISSUE THREAD

**Issue by JuanCaicedo** [okta/okta-sdk-nodejs#239]
Hi there!

I'm looking into updating a profile mapping for an IdP. I found that this is available through the API [here](https://developer.okta.com/docs/reference/api/mappings/), but don't find anything in the SDK for it. Taking a look at [generated-client.js](https://github.com/okta/okta-sdk-nodejs/blob/master/src/generated-client.js), I don't see anything that calls that url either ☹️

Are there plans to add this or any already open efforts? We will need to have this for our use case, so we will be building it out if not. We can contribute it back after 😀

**Comment by bretterer** [comment]
Hello @JuanCaicedo, Thanks for the feedback here.  We do currently have the mappings in our OpenAPI spec and I am not sure why we are not including this here. I will bring this up with our team to take a look at and get back to you. 

You can use the latest OpenAPI spec for your use case to see if it helps.  The spec is located at https://github.com/okta/okta-management-openapi-spec 

Internal Ref: OKTA-388870

**Comment by oleksandrpravosudko-okta** [comment]
@JuanCaicedo please checkout [5.0.0 release](https://github.com/okta/okta-sdk-nodejs/releases/tag/okta-sdk-nodejs-5.0.0) - it is based on latest SDK spec and includes Profile Mapping API methods.
