### ISSUE TITLE
Get a list of groups the user belongs to

### ISSUE THREAD

**Issue by kateloo** [okta/okta-sdk-nodejs#240]
Is there a way to do this? I tried several variations on client.getUser(userId).listGroups().each(group =>{});

**Comment by oleksandrpravosudko-okta** [comment]
Hi @kateloo. Does [client.listUserGroups(userId)](https://github.com/okta/okta-sdk-nodejs/blob/master/src/types/generated-client.d.ts#L474) suit your needs?

**Comment by kateloo** [comment]
This is perfect! Thank you @oleksandrpravosudko-okta!

**Comment by kateloo** [comment]
Here's how I'm accessing group names in typescript. Hope it helps:
    
```
            let groupNames: Array<string> = [];
            await _this.client.listUserGroups(userId).each(group => {
                groupNames.push( group.profile.name);
            }).catch(err => {
                //send user not found response
                httpStatus = 404;
                errorMessage = err;
            });
```

**Comment by kateloo** [comment]
Here's how I'm accessing group names in typescript. Hope it helps @ashutosh8 

```
            let groupNames: Array<string> = [];
            await _this.client.listUserGroups(userId).each(group => {
                groupNames.push( group.profile.name);
            }).catch(err => {
                //send user not found response
                httpStatus = 404;
                errorMessage = err;
            });
```

**Comment by kateloo** [comment]
Here's how I'm accessing group names in typescript. Hope it helps @ashutosh8

```
            let groupNames: Array<string> = [];
            await _this.client.listUserGroups(userId).each(group => {
                groupNames.push(group.profile.name);
            }).catch(err => {
                //send user not found response
                httpStatus = 404;
                errorMessage = err;
            });
```

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for posting the example @kateloo.

> I saw that it returns a collection but it is returning an object with nextUri 

@ashutosh8 in this case collection refers to a custom [class](https://github.com/okta/okta-sdk-nodejs#collection) instance - you should be able to access the resources it wraps with its [methods](https://github.com/okta/okta-sdk-nodejs/blob/master/src/types/collection.d.ts#L36).
