### ISSUE TITLE
Performance Issues with List Users

### ISSUE THREAD

**Issue by amcdnl** [okta/okta-sdk-nodejs#255]
## Issue
When running the following command:

```
await oktaClient.listUsers().each((user: any) => {
   items.push(user);
});
```

against an Okta instance that has 800+ users, this operation takes about 52s. If I take that same query and run it directly through the REST API like:

```
GET https://myaccount.okta.com/api/v1/users
```

This returns in roughly `661ms`. 

I realize that this is only returning a subset and not paging, however, if you say at 200 items per query * 4 queries thats still only roughly 4s ( not 52s ).

Furthermore I added some instrumentation that Datadog reports that the okta lambda is making roughly 881 HTTP GET calls!

![image](https://user-images.githubusercontent.com/227909/122220197-1b0d7500-ce7e-11eb-9836-fd9568db2383.png)

This makes me assume that its running these individually? 

When you combine this number of calls with multiple users all making similar calls I'm also getting rate limited.

## Versions
```
    "@okta/okta-sdk-nodejs": "^4.6.0"
```

**Comment by shuowu** [comment]
@amcdnl Thanks for reporting the issue!

Internal Ref: OKTA-404869

**Comment by amcdnl** [comment]
Any updates?

**Comment by oleksandrpravosudko-okta** [comment]
@amcdnl not at the moment, unfortunately.
OKTA-404869 is being worked on in the current sprint - I will report back once updates are available.

**Comment by oleksandrpravosudko-okta** [comment]
@amcdnl @apexskier does the issue manifest itself in a non-Lambda env? Are there any RequestExecutor customizations in place? Would you be able to add request [logging](https://github.com/okta/okta-sdk-nodejs#building-a-custom-request-executor) for debugging purposes?

Unwanted requests didn't seem to occur in my repro setup (both local and Lamda, SSWS/OAuth2, ~1500 dummy users, node 12/14).
<details>
  <summary>Cloudwatch events</summary>

  <img width="976" alt="Screenshot 2021-07-01 at 15 28 51" src="https://user-images.githubusercontent.com/71440851/124125384-384b6180-da82-11eb-8d41-8d01422742f2.png">
</details>

**Comment by amcdnl** [comment]
@oleksandrpravosudko-okta - Here is a screenshot of the logs using a custom requester with logging ( some are cut off ).

![image](https://user-images.githubusercontent.com/227909/124149415-8f3f3f80-da5e-11eb-88ac-76655951a5a7.png)

and here is the span list showing 44 HTTP requests to Okta API taking around 44s ( and timing out due to Lambda timeout restrictions ).

![image](https://user-images.githubusercontent.com/227909/124149718-ddecd980-da5e-11eb-9bd3-7727eb9acb40.png)

This okta instance has roughly 800 users and the code is extremely simple:

```
    const opts = query
      ? { q: query }
      : {};
    
    const collection = await client.listUsers(opts);

    await collection.each((user) => users.push(user));

    users.sort((a, b) => (a.profile.email > b.profile.email) ? 1 : -1);

    return { success: true, data: users };
```

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for sharing more details @amcdnl.

I have created a [sandbox](https://codesandbox.io/s/eager-euler-lzje9) with several endpoints retrieving users with either no SDK involvement (`/users/raw`) or using lower level methods (`/users/httpClient`, `/users/sdkClient`) - any chance you could test them against your org and see if any of them trigger request spikes?

**Comment by oleksandrpravosudko-okta** [comment]
Hi @amcdnl - have you been able to identify the cause/work around this issue?

**Comment by amcdnl** [comment]
@oleksandrpravosudko-okta - I was actually just getting back to looking into this. I'll let you know today.

**Comment by amcdnl** [comment]
OK - here are the results. Its got about 8k users so they all seem to align to the same response. I must have been doing something wrong in my tests that got me to this. 

I did find one interesting aspect is that I'd expect the SDK to cache per the documentation on the subsequent requests ( I moved the client outside of the function scope ) and it does not seem to. Any suggestions?

Raw
![image](https://user-images.githubusercontent.com/227909/128876258-7dd286ab-2546-4f6b-9820-4c662bd3164e.png)

SDK
![image](https://user-images.githubusercontent.com/227909/128876336-b33abcc4-a70f-48e4-946e-03f7d0ea1e7f.png)

HTTP
![image](https://user-images.githubusercontent.com/227909/128876401-00815c0b-27b6-4481-b70d-b4343fd70986.png)

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for running these tests!

It looks like collections requests are exempt from caching in default middleware: https://github.com/okta/okta-sdk-nodejs/blob/master/src/default-cache-middleware.js#L17

**Comment by oleksandrpravosudko-okta** [comment]
@amcdnl There seem to be no specific mention of this in past commits although my guess is that collections' requests are not cached because of pagination cursor [opaqueness](https://developer.okta.com/docs/reference/api-overview/#pagination).

+1 on caching limitation description - I created a story to document that:
Internal ref: OKTA-419120

**Comment by oleksandrpravosudko-okta** [comment]
Note on collections caching: https://github.com/okta/okta-sdk-nodejs/commit/42bef7c4c1a1cc8d40a8fd2ceccfcb35d4ae2947
