### ISSUE TITLE
Invalid search criteria when passing queryParameters to listApplications method

### ISSUE THREAD

**Issue by Shrirang97** [okta/okta-sdk-nodejs#272]
## Current behavior
    queryParameters = { filter: `user.id+eq+"` + userId + `"`, expand: 'user/' + userId };
    oktaClient
        .listApplications(queryParameters)
        .each(oktaApplication => {});

Doc Link: https://developer.okta.com/docs/reference/api/apps/#request-example-14

Behaviour: Giving error as `Invalid Search Criteria`

## Expected behavior

It should return list of applications

## Minimal reproduction of the problem with instructions

Try above code with then & catch.

## Environment

- OS: Mac
- Node.js version: 14.17.1

## Code issue 
https://github.com/okta/okta-sdk-nodejs/blob/master/src/generated-client.js

<img width="450" alt="Screenshot 2021-08-20 at 3 26 50 PM" src="https://user-images.githubusercontent.com/28738668/130216354-f4db25d1-c2b0-44de-a850-e4f249474629.png">

`qs.stringify` method is encoding characters like `+`, `"`, `\` in query parameters giving output as `%2B`, `%22`, `%2F`.

**Comment by Shrirang97** [comment]
Please assign this issue to me. I can fix this.

**Comment by denysoblohin-okta** [comment]
You should use " " instead of "+" in filter:
```js
queryParameters = { filter: `user.id eq "` + userId + `"`, expand: 'user/' + userId };
```
See [docs for filter](https://developer.okta.com/docs/reference/api/apps/#filters)

In [this example](https://developer.okta.com/docs/reference/api/apps/#request-example-14) " " is already encoded into "+" in request URL

**Comment by Shrirang97** [comment]
Thanks for pointing it out!
