### ISSUE TITLE
Security vulnerability in ansi-regex

### ISSUE THREAD

**Issue by nbeal** [okta/okta-sdk-nodejs#274]
## User story
ansi-regex@3.0.0 is currently vulnerable to a regular expression DoS attack. Currently fixed in v6.0.1. 

## Proposed solution
Update ansi-regex to v6.0.1

## Alternatives considered
Use a different package?

## Additional information
[CWE found here](https://cwe.mitre.org/data/definitions/400.html)

**Comment by aarongranick-okta** [comment]
@nbeal Thank you for the report! I have filed an internal issue (OKTA-428167). We will get this dependency updated.

**Comment by oleksandrpravosudko-okta** [comment]
@nbeal this is addressed in 6.0.0
