### ISSUE TITLE
code description is wrong

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-sdk-nodejs#276]
https://github.com/okta/okta-sdk-nodejs/blob/master/src/generated-client.js#L2892-L2899

description is wrong (copy-pasta)

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reporting this @gabrielsroka.

Doc strings are generated from the spec - this particular issue has been [fixed](https://github.com/okta/okta-management-openapi-spec/commit/f6f0c96a7ec5883b7942fc2ebdfaf6810d72cc05#diff-a49ad59390de288db9bb4779a8222b4f53470fe332fc2946c457d7328929daf7R4360) in v2.6.0 and will be resolved when SDK is generated using latest spec version.

**Comment by oleksandrpravosudko-okta** [comment]
Fixed in 6.0.0
