### ISSUE TITLE
Use library with ES5 apps

### ISSUE THREAD

**Issue by vurankar** [okta/okta-sdk-nodejs#28]
I am using the https://github.com/okta/okta-sdk-nodejs from a meteor node app not fully compatible with ES6 features yet.

Do you have a transpiled  version of the library to use with older apps ? 
Or are you open to a PR that allows this ?  https://github.com/okta/okta-sdk-nodejs/compare/master...vurankar:master 
or I am open to any other options that will get me rolling. 
I do not want to maintain a fork just for this reason.

**Comment by robertjd** [comment]
Hi @vurankar this library is intended to only be used in a protected server-side environment (because you must provide the client a sensitive API token).  For this reason we only support Nodejs >=4.8.3
