### ISSUE TITLE
Provide option to disable retry

### ISSUE THREAD

**Issue by petermorlion** [okta/okta-sdk-nodejs#294]
## User story
As a developer, I want to be able to choose if the SDK should retry (primary) authn calls, because a single call to the SDK means two calls to the API and so counts as two calls towards the lockout feature.

My app needs to make a call to the primary authn endpoint. Okta is set up to lock out users after 5 failed attempts. But because of the retry mechanism, it locks out the user when the user has done 3 failed attempts (because that amounted to 6 calls to the API).

## Proposed solution
Provide an option to disable the retries (or perhaps allow developers to provide a number to the SDK).

## Alternatives considered
One alternative is to increase the number of allowed failed attempts in Okta, but this is confusing and might interfere with other clients that don't use the SDK.

Another alternative is to not use the SDK, but that would mean missing one of the main features of the SDK: getting an access token for the current client.

**Comment by shuowu** [comment]
@petermorlion Thanks for reporting the issue! 

Internal Ref: OKTA-450308

**Comment by jaredperreault-okta** [comment]
@petermorlion Do you mind providing a code sample?

Secondly, are you trying to accomplish _end user_ authentication? If so, you may want to take a look at [auth-js](https://github.com/okta/okta-auth-js), it is specifically designed for end user authentication flows. This sdk (okta-sdk-nodejs) is designed for interacting with the Okta APIs (like the Management API).

**Comment by petermorlion** [comment]
@jaredperreault-okta my code does nothing too special. This is what it looks like simplified:

```
const client = new okta.Client({
    orgUrl: "...",
    authorizationMode: "PrivateKey",
    clientId: "...",
    scopes: ["okta.users.read"],
    privateKey: privateKey
});

const result = await client.http.post(`${oktaAuthnUri}/api/v1/authn`, {
    headers: {
        "Content-Type": "application/json"
    },
    body: JSON.stringify({
        username: email,
        password: password
    })
});

const responseBody: PrimaryAuthnResponse = await result.json();
```

(we use TypeScript)

As for our usage, it is in fact an older application that handled OAuth flows using another platform as user store. We now have a scenario where we want/need to use Okta as a user store. So in essence, we want to check if the user provided a correct username and password, nothing more.

If I'm correct, we can use the authn-js library's `signInWithCredentials` function to check if the transaction was a success. But then, contrary to the code sample, just continue as we did instead of calling `setCookieAndRedirect`. Something like this:

```
const transaction = await authClient.signInWithCredentials({
    username: 'some-username',
    password: 'some-password'
});

if (transaction.status !== "SUCCESS") {
    throw new Error();
}

// continue our logic
```

Would my thinking be correct? As far as I can see, there is no automatic retry in that library (or the underlying [cross-fetch](https://github.com/lquixada/cross-fetch)).

**Comment by jaredperreault-okta** [comment]
[auth-js](https://github.com/okta/okta-auth-js)'s `signInWithCredentials` will verify the user credentials and will not automatically retry upon bad credentials. You do not need to call `setCookieAndRedirect`, but your logic will want to return the credentials to the user's client for future authorization checks. 

signInWithCredentials [docs](https://github.com/okta/okta-auth-js/blob/master/docs/authn.md#signinwithcredentialsoptions)

These samples may also be helpful [auth-js samples](https://github.com/okta/okta-auth-js/tree/master/samples/generated)

**Comment by petermorlion** [comment]
@jaredperreault-okta Great, thanks for the pointer. Then that is the way forward for us.
