### ISSUE TITLE
Question: Object.defineProperty() in Resource constructor, is it really needed?

### ISSUE THREAD

**Issue by d-asensio** [okta/okta-sdk-nodejs#32]
Hi,

I have a question for you guys! Looking at the nitty-gritty of your code I've found this:

https://github.com/okta/okta-sdk-nodejs/blob/0bb6f63e890c7b192603fdf00c67575126e55b68/src/resource.js#L22-L26

And I don't get the "why" of the Object.defineProperty() usage, since the [MDN docs > Object > defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)  say that descriptor's "enumerable" key is `false` by default.

Thanks in advance!

**Comment by robertjd** [comment]
Thanks for noticing this!  You're right, enumerable does default to false.  Seems like we were trying to revert the explicit property assignment in line 22, but that line should't have been there to begin with.  I just opened #33 to fix this.
