### ISSUE TITLE
Mismatch in stable major release statuses in README

### ISSUE THREAD

**Issue by maxpollard** [okta/okta-sdk-nodejs#321]
### Describe the bug?

The readme statese the following: 

✔️: The current stable major version series is: 4.x.x

However directly below it states 

4.x | ❌ Retired

### What is expected to happen?

I would expect the current stable release is 5.x or 6.x?

### What is the actual behavior?

N/A

### Reproduction Steps?

N/A

### SDK Versions

N/A

### Execution Environment

N/A

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for flagging this @maxpollard. Updated in https://github.com/okta/okta-sdk-nodejs/commit/105cc67b700881795c39489b14776e6ca5b3571a
