### ISSUE TITLE
MemoryStore get function signature does not align with TypeScript definition 

### ISSUE THREAD

**Issue by SamMurphyDev** [okta/okta-sdk-nodejs#363]
### Describe the bug?

The CacheStorage interface and by implementation the MemoryStore class, the get function has a signature of `get(key: string): Promise<string>;` https://github.com/okta/okta-sdk-nodejs/blob/master/src/types/memory-store.d.ts#L16

The actual implementation of the MemoryStore has a function signature of `get(key: string): Promise<string | undefined>;` https://github.com/okta/okta-sdk-nodejs/blob/master/src/memory-store.js#L35-L49

### What is expected to happen?

Type defintions should align with reference implemetation

### What is the actual behavior?

The function signature expects a string to always be returned in the promise

### Reproduction Steps?

See description. Type alignment issue, not an actual implementation issue.

### SDK Versions

"@okta/okta-sdk-nodejs": "^6.5.0",

### Execution Environment

NodeJS, Ubuntu

**Comment by oleksandrpravosudko-okta** [comment]
Released in [6.6.0](https://github.com/okta/okta-sdk-nodejs/releases/tag/okta-sdk-nodejs-6.6.0)
