### ISSUE TITLE
Support a custom authorization server endpoint for the clients oauth methods

### ISSUE THREAD

**Issue by hershmire** [okta/okta-sdk-nodejs#368]
### Describe the feature request?

I'd like to be able to define a custom Okta authorization server (e.g. `https://${yourOktaDomain}/oauth2/{customAuthId}/v1/token/`) that this SDK would use when executing the client's `oauth` methods. It appears that this is not currently configurable and instead [hardcodes this value as `/oauth2/v1/token`](https://github.com/okta/okta-sdk-nodejs/blob/master/src/oauth.js#L47). If that allowed for `/oauth2/{customAuthId}/v1/token`, the below code would work successfully.

SDK usage:

```js
const okta = require("@okta/okta-sdk-nodejs");

const client = new okta.Client({
  orgUrl: "https://${yourOktaDomain}",
  authorizationMode: "PrivateKey",
  clientId: "client-id",
  scopes: ["customScope"],
  privateKey: {
    ...privateKey
  },
  keyId: "kid...",
});

async function getAccessToken() {
  try {
    // client.oauth.getAccessToken() hardcodes the endpoint. Maybe accept a param
    // and/or allow it to be configurable on the creation of the client?
    const accessToken = await client.oauth.getAccessToken();

    console.log("accessToken:", accessToken);
    // expected to return like the following:
    // {
    //    "access_token": "eyJhbG[...]1LQ",
    //    "token_type": "Bearer",
    //     "expires_in": 3600,
    //     "scope": "customScope"
    // }
  } catch (err) {
    console.log("Error:", err);
  }
}

getAccessToken();
```

Following Okta's docs around [requesting a token for the Client Credentials grant](https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#request-for-token) I can achieve this via a cURL:

```bash
curl --request POST \
  --url https://${yourOktaDomain}/oauth2/{customAuthId}/v1/token \
  --header 'accept: application/json' \
  --header 'authorization: Basic MG9hY...' \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&scope=customScope'
```

### New or Affected Resource(s)

OAuth: `client.oauth.getAccessToken()`

### Provide a documentation link

https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/

**Comment by hershmire** [comment]
Hello, any update on this?

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: OKTA-570183

**Comment by hershmire** [comment]
@denysoblohin-okta is there a way for us to have visibility into that?

**Comment by denysoblohin-okta** [comment]
@hershmire 
Sorry for confusion.
But you can't use custom authorization server for the purposes of this Node.js SDK librrary.
Only default Org authorization server can mint access tokens with Okta API Scopes, eg. `okta.users.manage`
https://developer.okta.com/docs/concepts/auth-servers/#which-authorization-server-should-you-use
https://developer.okta.com/docs/guides/implement-oauth-for-okta/main/#about-oauth-2-0-for-okta-api-endpoints
