### ISSUE TITLE
DeviceApi is missing in sdk client

### ISSUE THREAD

**Issue by julron** [okta/okta-sdk-nodejs#386]
### Describe the feature request?

DeviceApi (ObjectDeviceApi) is missing in list of `Client` object apis

### New or Affected Resource(s)

7.0.0

### Provide a documentation link

https://github.com/okta/okta-sdk-nodejs/blob/26ba0a02e6e0b96467014f5125a370668416e881/src/types/generated/types/ObjectParamAPI.d.ts#L3770

### Additional Information?

Is it possible to add `deviceApi` to the client as well?
Thank you

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue. `deviceApi`  should be added to client.
Internal ref: OKTA-602351

**Comment by az-nextsec** [comment]
I still can't see it in version 7.0.1 which is the latest version?

**Comment by az-nextsec** [comment]
@denysoblohin-okta I am happy to show you that it is not available.

If you download your source code from this repo as of 7.0.1 tag it is NOT included:
https://github.com/okta/okta-sdk-nodejs/releases/tag/okta-sdk-nodejs-7.0.1

**Comment by az-nextsec** [comment]
You can also see it in the github tree here, DevicesApi is not imported. It is present on master, but NOT in 7.0.1

https://github.com/okta/okta-sdk-nodejs/blob/okta-sdk-nodejs-7.0.1/src/client.js#L55

**Comment by az-nextsec** [comment]
@denysoblohin-okta you can see in master it is on line 56, but not in 7.0.1

https://github.com/okta/okta-sdk-nodejs/blob/master/src/client.js#L56

**Comment by denysoblohin-okta** [comment]
Sorry, you're correct. 
New version 7.1.0 should be released, it will contain `DeviceApi`

**Comment by az-nextsec** [comment]
@denysoblohin-okta do you have an ETA for this?

**Comment by sutru** [comment]
this fix appears to still be missing a listDeviceUsers method

**Comment by denysoblohin-okta** [comment]
@az-nextsec 
Please update to 7.1.0
