### ISSUE TITLE
Discrepancies migrating from v6.6.0 to v7.0.0

### ISSUE THREAD

**Issue by renacargnelutti** [okta/okta-sdk-nodejs#387]
### Describe the bug

Hello guys! I hope you are doing well.

I'm just trying to bump the version from 6.6.0 to 7.0.0 and I just noticed there are some changes in `Application` interface. For example: the `credentials` and `settings` fields are gone, so I won't have access to that info when retrieving some application. Should I adjust my code in order to fit with these new changes?

PS: The migration guide is so simple and I would like to know if there is another document where I can see the changes in a deeper way.

### Reproduction Steps?

- I updated the `package.json` `@okta/okta-sdk-nodejs` library to `7.0.0`.
- I got some type errors since `Application` interface has changed.

### SDK Versions

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 73.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
    
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
    
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.3
    
  npmPackages:
    @okta/jwt-verifier: ^3.0.1 => 3.0.1
    @okta/okta-sdk-nodejs: ^6.6.0 => 7.0.0

**Comment by denysoblohin-okta** [comment]
In v7 `Application` is a base class. Please use one of classes that extends `Application`:
- AutoLoginApplication
- BasicAuthApplication
- BookmarkApplication
- BrowserPluginApplication
- OpenIdConnectApplication
- SamlApplication
- SecurePasswordStoreApplication
- WsFederationApplication

```js
const app: BookmarkApplication = await client.applicationApi.getApplication({appId});
// use app.settings
```

**Comment by renacargnelutti** [comment]
Thanks a lot for the explanation 🙌
