### ISSUE TITLE
ApplicationApi.js no longer has "name" property.

### ISSUE THREAD

**Issue by zachpuck** [okta/okta-sdk-nodejs#399]
### Describe the bug

When calling the node.js sdk for `OktaClient.applicationApi.listApplications()` I am expecting to receive apps that include a `name` property but instead this property is missing. 

other properties like `id` and `label` still exist. 

other SDK's continue to include this property. Ex: [golang sdk](https://github.com/okta/okta-sdk-golang/blob/b145286aeae96f4e5173640a537769ded8342cc0/okta/application.go#L50)

### Reproduction Steps?

Utilize the node sdk and call the `applicationApi.listApplications()` method to return a collection of Applications. each Applications properties include fields like `id` and `labels` but is missing `name`. 

### SDK Versions

7.0.0

**Comment by denysoblohin-okta** [comment]
In v7 `Application` is a base class. You can cast application instance to one of classes that extends `Application` (depending on `signOnMode`):
- AutoLoginApplication
- BasicAuthApplication
- BookmarkApplication
- BrowserPluginApplication
- OpenIdConnectApplication
- SamlApplication
- SecurePasswordStoreApplication
- WsFederationApplication

Base class does not have `name` property, but listed classes have `name`.
This comes from OpenApi v3 spec
