### ISSUE TITLE
DevicesApi is missing from latest published npm version

### ISSUE THREAD

**Issue by az-nextsec** [okta/okta-sdk-nodejs#407]
### Describe the bug

In the 7.0.1 client `DevicesApi` is missing because it is simply not added in `client.js` even though it is there in `DevicesApi.js`.

On `master` branch that api is there. But it is not published on npm

### Reproduction Steps?

Install latest version via npm install

### SDK Versions

7.0.1

**Comment by az-nextsec** [comment]
You can see in the repository that the DevicesApi is not included in 7.0.1 but is included in master

https://github.com/okta/okta-sdk-nodejs/blob/okta-sdk-nodejs-7.0.1/src/client.js#L55

https://github.com/okta/okta-sdk-nodejs/blob/master/src/client.js#L56

**Comment by az-nextsec** [comment]
Supposedly this will be addressed in `7.1.0` except there is no ETA yet on when that is available: https://github.com/okta/okta-sdk-nodejs/issues/386#issuecomment-1929152520

**Comment by bgirardeau-figma** [comment]
@denysoblohin-okta any update on this? It's almost been a year since the API was added without being released

**Comment by denysoblohin-okta** [comment]
Please update to 7.1.0
