### ISSUE TITLE
Collection promises don't allow process to exit

### ISSUE THREAD

**Issue by robertjd** [okta/okta-sdk-nodejs#45]
With this basic usage of our collection instances, the process will not exit after the collection each() promise is fulfilled:

```
const okta = require('@okta/okta-sdk-nodejs');
const client = new okta.Client({
  orgUrl: 'https://{yourOktaDomain}.com/',
  token: '{your_api_token}',
})

client.listUsers()
.each(user => {
  console.log(user);
})
.then(() => {
  // this line gets hit, but the process does not terminate
  console.log('All users have been visited');
})
.catch((err) => {
  console.log(err);
})
```

**Comment by jmelberg-okta** [comment]
This bug looks like it is caused by an indefinite [`timeInterval`](https://github.com/okta/okta-sdk-nodejs/blob/master/src/memory-store.js#L22-L31) being set and never exited. 

To work around this you can disable it during the instantiation of your client:

```javascript
const okta = require('@okta/okta-sdk-nodejs');
const MemoryStore = require('@okta/okta-sdk-nodejs/src/memory-store');

const client = new okta.Client({
  orgUrl: 'https://{yourOktaDomain}.com/',
  token: '{apiToken}',
  cacheStore: new MemoryStore({
    keyLimit: 100000,
    expirationPoll: null
  })
})
```

**Comment by rdegges** [comment]
Note: this happens even if you only create a client. I'm at a hackathon atm and this tripped a lot of people up. Creating a client alone would cause the web server to never exit in lambda functions which broke a lot of functionality.

**Comment by austinkelleher** [comment]
I just ran into this. I would like to propose introducing a `close` function on the `okta.Client` class. This `close` function would be used for cleanup like clearing the interval in the `MemoryStore` if it's being used (and perhaps other cleanup in the future). Calling the close function would only be necessary if you want to force cleanup. What are you thoughts @jmelberg-okta @robertjd @lboyette-okta @rdegges? 

**I would be happy to introduce this fix in a PR if we decide that it is a good idea.**

Usage:

```js
const okta = require('@okta/okta-sdk-nodejs');

const client = new okta.Client({
  orgUrl: 'https://{yourOktaDomain}.com/',
  token: '{apiToken}'
})

// Make some awesome Okta API calls right here

client.close() // All done! My script doesn't hang anymore!
```

**Comment by austinkelleher** [comment]
Thoughts on the above @rdegges @jmelberg-okta? I'd be happy to submit a PR if the above API sounds good.

**Comment by rdegges** [comment]
Ping @robertdamphousse-okta. I'd love to help out here but I'm not in charge of this project and don't wanna speak for Rob =)

**Comment by austinkelleher** [comment]
Hey @robertdamphousse-okta thoughts on my proposal?

**Comment by arnaudknobloch** [comment]
I would also like to have a fix for this.

**Comment by robertjd** [comment]
Hi all, thanks for the notes.  @austinkelleher we'll take a look at your proposal when we pick this up for work, I'd also like to evaluate our cache manager and maybe find a more transparent workaround.  I can't guarantee when we'll be able to work on this, but I'm going to put this in our Triaged column (which means we do want to fix this).  Thanks!

**Comment by leifdreizler** [comment]
+1 to addressing this and updating the examples. Just spent some time debugging why my node script wasn't exiting 😬

**Comment by robertjd** [comment]
In the 2.x release of this SDK, the memory store polling is now disabled by default and must be opted into.
