### ISSUE TITLE
Fix Typo on Readme

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-sdk-nodejs#48]
First off, just want to say awesome sdk!  One quick thing i noticed is that is the first part of the readme docs on initialization a "," is missing.
referring to this below.

const client = new okta.Client({
  orgUrl: 'https://dev-1234.oktapreview.com/'
  token: 'xYzabc'    // Obtained from Developer Dashboard
});

just a quick comma between them.  Really is very minor, but just thought I would add.

**Comment by nbarbettini** [comment]
Thanks for the catch @andrewvanbeek-okta! We accept PRs 😉

**Comment by robertjd** [comment]
Thanks @andrewvanbeek-okta !
