### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by kspearrin** [okta/okta-sdk-nodejs#52]
It would be nice if there were TypeScript definitions for this SDK. Thanks!

**Comment by jiyuhan** [comment]
This is much needed. Is anybody working on this, or having a plan for this?

**Comment by Shahaed** [comment]
I agree. It is unacceptable

**Comment by leifdreizler** [comment]
+1 to having TypeScript Definitions 👍

**Comment by rafakwolf** [comment]
+1 :D

**Comment by swiftone** [comment]
Your comments are not ignored, this is just competing with all the various new features and quality of life improvements.   For now continue to vote for this issue if you'd like to see us focus on it and we'll improve our communication in return.

**Comment by smithki** [comment]
Between this and okta/okta-auth-js#64, I think it's pretty clear there is a wide need for TypeScript typings. This lack makes Okta a tough sell to the engineering managers! 😉

**Comment by nbarbettini** [comment]
@smithki Understood, thanks for your feedback!

**Comment by Shahaed** [comment]
1 year later! Good support!

**Comment by eropple** [comment]
@Shahaed I'm looking forward to TypeScript definitions as much as anyone, but there is absolutely no call for being a jerk about it.

**Comment by eduardomourar** [comment]
As a good starting point, [this blog](https://www.stevefenton.co.uk/2013/01/complex-typescript-definitions-made-easy/) should be looked and this library to generate the definitions [here](https://github.com/Microsoft/dts-gen) as well.

**Comment by Shahaed** [comment]
> @Shahaed I'm looking forward to TypeScript definitions as much as anyone, but there is absolutely no call for being a jerk about it.

And there is absolutely no call for being overly nice about a near critical feature (from a PAID service) for all codebases converting to TypeScript. 🤷‍♂@eropple

**Comment by jnelken** [comment]
Anyone care to share what they've made so far? Maybe we can crowdsource something. I found a few basic return types here https://developer.okta.com/blog/2019/09/19/nodejs-typescript

**Comment by robertjd** [comment]
Hi everyone, thank you for your thoughts.  We've discussed this and have decided that Typescript should get some first-party support from us, so we will start working it into our roadmap.  Continue to watch this issue for updates.  Thanks!

**Comment by shellscape** [comment]
@robertjd we're past two years open on this issue and I see nothing public addressing this since your last comment. TypeScript is no longer niche. what's the word?

**Comment by swiftone** [comment]
Adding Typescript definitions to our work is actively on people's sprints, but does bounce around as priority issues appear.  I don't have a more specific answer than that: The work isn't theoretical, it is actively happening, and you should start seeing it appear on our various repos.

**Comment by Ziao** [comment]
Just adding my $0.02. This is actively scaring away potential customers. I for one wouldn't even consider using a library that does not have definitions available when it is going to play such an important role in my applications. I don't believe I am the only one with this opinion. 
Not trying to be an ass, just sharing my point of view.

**Comment by myspivey** [comment]
We are potential customers and I want to gently agree here. I spent a great deal of time this weekend trying to figure out why something was failing that was listed in the docs only to figure out the docs were wrong. This would have been pretty clear cut with types giving me a hint that things were out of sync between implementation and docs.

**Comment by swiftone** [comment]
@Ziao and @myspivey - We appreciate the feedback.  Typescript definitions are being actively pursued, we are just taking some time to (1) do the projects in dependency order and (2) make sure we're doing it right and maintainably, as we feel poor or out-of-date definitions are worse than none.

Definitely keep sharing your comments - we are listening and we understand the delays are frustrating.

**Comment by swiftone** [comment]
Just a periodic update: We are rolling out TypeScript definitions in one of our more heavily-depended libraries.  If that goes smoothly, other libraries will be updated with TypeScript definitions, including this one.

You can view that other TypeScript deployment here: https://github.com/okta/okta-auth-js/pull/413

**Comment by oleksandrpravosudko-okta** [comment]
TypeScripts definitions are available in [4.5.0](https://github.com/okta/okta-sdk-nodejs/releases/tag/okta-sdk-nodejs-4.5.0). (cc @mraible)

**Comment by mraible** [comment]
Correct me if I'm wrong, but this means we have TypeScript support in *all* our JS SDKs! 😃😁😆

**Comment by tsibelman** [comment]
Is there any example I can check ?

**Comment by oleksandrpravosudko-okta** [comment]
@tsibelman I have pushed a naive usage example [here](https://github.com/okta/okta-sdk-nodejs/tree/op-ts-signature-fix#typescript-usage-examples-450). 

It looks like there is an issue with generated client's `create*` and `update*` method signatures - I will create a follow-up PR to address that. Sorry for inconvenience.

**Comment by tsibelman** [comment]
@oleksandrpravosudko-okta Thank you for this

**Comment by oleksandrpravosudko-okta** [comment]
@tsibelman Please check out [4.5.1](https://github.com/okta/okta-sdk-nodejs/releases/tag/okta-sdk-nodejs-4.5.1) release. The [README](https://github.com/okta/okta-sdk-nodejs/tree/4.5#typescript-usage-examples-450) has been updated with a suggested usage example.

**Comment by tsibelman** [comment]
It looks great I changed my code and all is working fine, but I think if you can move all models declaration to a root of the library it could make type a bit more discoverable compared to '@okta/okta-sdk-nodejs/src/types/models/LogEvent'

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the feedback @tsibelman.
Moving model declarations to a root of the library also requires updating JS [exports](https://github.com/okta/okta-sdk-nodejs/blob/master/src/index.js) in the same way, otherwise users might end up referencing non-existent models at runtime when attempting to instantiate them. I believe this will be done in future releases, when ES modules support is introduced to this library.

**Comment by shellscape** [comment]
@oleksandrpravosudko-okta the established pattern for a move of exports _now_ would be to move the exports, duplicate them to the old spot, and deprecate the old spot. That's an extremely common pattern to follow when initial choices that users may now depend on need to be refined. I'd really encourage you fine folks there at Okta to embrace common open source patterns in Okta's open source libs.

**Comment by shellscape** [comment]
@oleksandrpravosudko-okta it's been over a month with no reply to the last comment. since this issue has been open since 2018, the work I described is rather trivial, and this package is maintained by a corporate entity, it would be cool if you could at least give us (who are mostly working for orgs that pay for Okta) an idea of timeline.

**Comment by oleksandrpravosudko-okta** [comment]
Apologies for the lack of updates here @shellscape.
The suggestion you made was implemented in this [#237](https://github.com/okta/okta-sdk-nodejs/pull/237) and will be released in 4.6.0. I will post another update when the release timeline is known.

**Comment by shellscape** [comment]
Wonderful, thank you very much.
