### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-sdk-nodejs#59]
- [ ] Update this repo's README to match the [new template](https://gist.github.com/nbarbettini/c0f44cf08b6d99b39cd59e533842a684). See the [Java SDK readme](https://github.com/okta/okta-sdk-java/blob/master/README.md) for inspiration.
- [ ] For version info, the latest stable series is 1.x, and the 0.x series is retired. 
- [ ] Since there is not (yet) an authentication SDK for Node, refer readers to the [Authentication API](https://developer.okta.com/docs/api/resources/authn).
- [ ] Let me know if any of the sample prompts in the template don't apply.

**Comment by shuowu** [comment]
Looks like the repo is still using the old template, update needed.

Internal Ref: OKTA-404875

**Comment by oleksandrpravosudko-okta** [comment]
Addressed in https://github.com/okta/okta-sdk-nodejs/pull/262, https://github.com/okta/okta-sdk-nodejs/pull/265
