### ISSUE TITLE
listUsers doesn't paginate

### ISSUE THREAD

**Issue by rdegges** [okta/okta-sdk-nodejs#77]
I'm writing a simple script which attempts to enumerate through every user in my org. I have roughly 5k users.

When I run the following script:

```javascript
const client = new okta.Client({
  orgUrl: "https://dev-842917.oktapreview.com",
  token: "xxx",
  requestExecutor: new okta.DefaultRequestExecutor()
});

let total = 0;
client.listUsers().each(user => {
  console.log(user);
  total++;
}).then(() => {
  console.log("Listed " + total + " users.");
  process.exit();
});
```

It only iterates through 199 users then stops. Looks like it fetches maybe one or two pages of results and gives up? Any idea why?

**Comment by robertjd** [comment]
@rdegges are you still having this issue? I just tried your code and was able to list all 438 users in my test org.

**Comment by manueltanzi-okta** [comment]
@rdegges are you still having this issue?

**Comment by swiftone** [comment]
Closing as not reproducible - feel free to reopen if the problem still exists.

**Comment by rdegges** [comment]
Yo... What's the deal with closing? It's 100% reproducible... Just ran this again with the same results. I have over 5k users in my org and the script only shows 575 for some reason.

That's why I copied the entire script into the issue so anyone could run it to repro.

**Comment by rdegges** [comment]
If you're having issues reproducing, shoot me a PM on Slack and I'll give you access to my test org so you can use my stuff if you want. I've got several orgs that all have > several hundred users and I can reproduce this on every single one.

**Comment by kspearrin** [comment]
Is there no update to this bug? It's been nearly two years since it was reported. I am hitting the same issue. What's the workaround? I don't see any way to manually handle the paging in the SDK.

**Comment by kspearrin** [comment]
After looking into this a bit more, it seems the issue is likely that this library is using fetch APIs and fetch APIs do not return the `link` response header in CORS situations. This is only reproducible in a browser scenario.

**Comment by shuowu** [comment]
@kspearrin looks like the issue is caused by the default implementation of the `request executor`, please refer to [Building a Custom Request Executor](https://github.com/okta/okta-sdk-nodejs#building-a-custom-request-executor) to replace the underlying fetch method implementation.

**Comment by rdegges** [comment]
This has been resolved in the latest SDK release from what I can tell. I'm going to close this out.
