### ISSUE TITLE
Travis error when running tests: "Error: Okta API token not provided"

### ISSUE THREAD

**Issue by kevlened** [okta/okta-sdk-nodejs#84]
This PR is failing, despite it being a non-functional change: #83 
Travis results: https://travis-ci.org/okta/okta-sdk-nodejs/jobs/462938531

Oddly, this only happens in the Node 8 tests.

**Comment by oleksandrpravosudko-okta** [comment]
Closing this issue as Node 8 support has ceased, integration tests are now running on internal CI.
